"""message

Revision ID: 759060603696
Revises: a39a50d18d6e
Create Date: 2024-01-17 22:01:37.725752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759060603696'
down_revision = 'a39a50d18d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('location')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
