"""refactor models

Revision ID: c007db29a515
Revises: 759060603696
Create Date: 2024-01-17 23:46:41.479612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c007db29a515'
down_revision = '759060603696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_blogs_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blogs'))
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('receiver', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver'], ['users.id'], name=op.f('fk_messages_receiver_users')),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], name=op.f('fk_messages_sender_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['blogs.id'], name=op.f('fk_comments_article_id_blogs')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.drop_table('profiles')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_constraint('fk_friendships_req_user_id_profiles', type_='foreignkey')
        batch_op.drop_constraint('fk_friendships_rec_user_id_profiles', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_friendships_rec_user_id_users'), 'users', ['rec_user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_friendships_req_user_id_users'), 'users', ['req_user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.String(), nullable=True))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('birthday')
        batch_op.drop_column('telephone')
        batch_op.drop_column('username')

    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_friendships_req_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendships_rec_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_friendships_rec_user_id_profiles', 'profiles', ['rec_user_id'], ['id'])
        batch_op.create_foreign_key('fk_friendships_req_user_id_profiles', 'profiles', ['req_user_id'], ['id'])

    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('bio', sa.VARCHAR(), nullable=True),
    sa.Column('location', sa.VARCHAR(), nullable=True),
    sa.Column('photo_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_profiles')
    )
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('messages')
    op.drop_table('blogs')
    # ### end Alembic commands ###
